### ISSUE TITLE
3.0.0 release checklist

### ISSUE THREAD

**Issue by wazzamatazz** [intelligentplant/AppStoreConnect.Adapters#277]
- [x] Check for last-minute CVE fixes in referenced packages
- [x] Remove pre-release flag from `version.json` and `Directory.Build.props`
- [x] Update tutorial source code to reference 3.0.0 release packages
- [x] Review main README.md for accuracy
- [x] Prepare release notes
- [x] Create `release/3.0.0` branch
- [x] Build and sign packages from `release/3.0.0` branch
- [x] Publish packages to NuGet.org
- [x] Mark [IntelligentPlant.AppStoreConnect.Adapter.Json](https://www.nuget.org/packages/IntelligentPlant.AppStoreConnect.Adapter.Json) package as deprecated
- [x] Publish release and tag from `release/3.0.0` branch
- [x] Pull `release/3.0.0` into `main`
