### ISSUE TITLE
4.0.0 release checklist

### ISSUE THREAD

**Issue by wazzamatazz** [intelligentplant/AppStoreConnect.Adapters#312]
- [x] Move all API changes from `PublicAPI.Unshipped.txt` files to `PublicAPI.Shipped.txt`
- [x] Check for last-minute CVE fixes in referenced packages
- [x] Remove pre-release flag from `version.json` and `Directory.Build.props`
- [x] Update tutorial source code to reference 4.0.0 release packages
- [x] Review main README.md for accuracy
- [x] Prepare release notes
- [x] Build and sign release packages
- [x] Publish packages to NuGet.org
- [x] Tag release source code
- [x] Pull `develop/4.0.0` into `main`
- [x] Delete `develop/4.0.0` and make `main` the default branch
